### ISSUE TITLE
Bar Chart Code in TCL.html

### ISSUE THREAD

**Issue by angelijp** [DATA300L111-20S/Project-Zero-TCL#2]
I've added the bar chart code under figure id="bar-chart" code in our main TCL.html file, however, the visualizations crash when this code runs. When I remove most or all of the code, it runs perfectly fine. I'm wondering if the CSS styling has anything to do with the breakage of the visualizations.

**Comment by Tientuine** [comment]
In TestBar.html, you were loading D3 version 3. In TCL.html, you are using the local d3.js in your repository, which is D3 version 5. There are some differences between the versions that are incompatible. If you look at the browser error console, you'll see that there is an error with `d3.scale`. In D3v5, instead of `d3.scale.ordinal` you need to use `d3.scaleOrdinal`. There may be other differences as well - I recommend that you follow the D3 documentation itself to make sure that you're using the right function names and passing the right arguments. Here is the GitHub page for scales: https://github.com/d3/d3-scale .
