### ISSUE TITLE
Tooltip and Axis

### ISSUE THREAD

**Issue by angelijp** [DATA300L111-20S/Project-Zero-TCL#5]
In updating the most recent TCL file, I get everything to show up properly except for the tooltip for the bar chart and the y2 axis label. The tooltip in the original file normally popped at the bottom left-hand corner showing the exact number of TCL in KHA but now it doesn't pop up. Still, nothing shows even when I updated the CSS file. Could I be that the SVG is still confined in too tight of space?

**Comment by Tientuine** [comment]
I'll pull and review the latest code to confirm, but my guess is that you were computing the position of the tooltip based on the width and/or height attributes of the SVG, and now that you've switched to viewBox instead there are no width and height attributes so that position calculation is producing a NaN (not-a-number) value, so the browser doesn't know where to draw the tooltip.

**Comment by Tientuine** [comment]
Nope, I was wrong! The problem is actually that the `tooltip` variable is undefined at the point in the code where you are trying to use it. Here are some screenshots showing the error messages I see in Chrome (though some other errors occur even before the tooltip problem).
![errors](https://user-images.githubusercontent.com/1669148/81935622-ebc36f00-95be-11ea-9b4d-bd2ad75d1768.png)
![tooltip-errors](https://user-images.githubusercontent.com/1669148/81935618-eb2ad880-95be-11ea-892b-cc9e77795452.png)
